# Generated by Django 4.1.5 on 2023-02-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_no',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='Registration No'),
        ),
    ]
