# Generated by Django 4.1.5 on 2023-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_entry',
            field=models.BooleanField(db_index=True, default=False, help_text='Check if you want to add this product to the carousel'),
        ),
    ]
