# Generated by Django 4.1.5 on 2023-01-27 17:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=filer.fields.image.FilerImageField(help_text='Upload the image of the category', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
