# Generated by Django 4.1.5 on 2023-02-23 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('main', '0002_alter_order_options_product_carousel_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_carousel_images',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='carousel_images', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
