# Generated by Django 4.1.5 on 2023-01-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orderedproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='user',
        ),
    ]
